//! Protocol generation — transforms analysis results into structured
//! troubleshooting decision trees written as Markdown files.
//!
//! Produces two outputs:
//! - Per-project `.troubleshooting.md` — project-specific protocols
//! - Global `~/projects/.troubleshooting-global.md` — cross-project patterns

use std::fs;
use std::path::Path;

use crate::analyzer::{EcosystemAnalysis, ErrorClass, ProjectAnalysis};

/// Generate all troubleshooting protocols from an ecosystem analysis.
pub fn generate_protocols(analysis: &EcosystemAnalysis, projects_dir: &Path) {
    // Per-project protocols
    for project in &analysis.per_project {
        if !project.recurring_errors.is_empty() {
            generate_project_protocol(project);
        }
    }

    // Global cross-project protocol
    if !analysis.cross_project_patterns.is_empty() || !analysis.top_categories.is_empty() {
        generate_global_protocol(analysis, projects_dir);
    }
}

/// Generate a project-specific troubleshooting protocol.
fn generate_project_protocol(project: &ProjectAnalysis) {
    let path = project.project_dir.join(".troubleshooting.md");
    let mut out = String::new();

    out.push_str(&format!("# {} — Troubleshooting Protocol\n\n", project.project_name));
    out.push_str(&format!(
        "> Auto-generated by orrchestrator retrospect engine. {} unique errors, {:.0}% resolved.\n\n",
        project.unique_errors,
        project.resolution_rate * 100.0,
    ));

    if let Some(avg) = project.avg_resolution_time {
        out.push_str(&format!("Average resolution time: {}\n\n", format_duration(avg)));
    }

    // Group by category for decision tree structure
    let mut by_category: std::collections::BTreeMap<&str, Vec<&ErrorClass>> = std::collections::BTreeMap::new();
    for error in &project.recurring_errors {
        by_category.entry(error.category.label()).or_default().push(error);
    }

    for (category, errors) in &by_category {
        out.push_str(&format!("## {}\n\n", capitalize(category)));

        for error in errors {
            let status = if error.resolved { "RESOLVED" } else { "OPEN" };
            let count_label = if error.occurrence_count > 1 {
                format!(" (×{})", error.occurrence_count)
            } else {
                String::new()
            };
            out.push_str(&format!("### [{status}]{count_label} `{}`\n\n", truncate(&error.fingerprint, 60)));
            out.push_str(&format!("**Symptom:**\n```\n{}\n```\n\n", truncate(&error.sample_context, 150)));

            if let Some(ref resolution) = error.resolution {
                // Extract the actionable part (skip "Auto-resolved after..." prefix)
                let fix = if let Some(ctx) = resolution.strip_prefix("Auto-resolved after continued output. Post-error context:\n") {
                    format!("Session continued successfully after error. Context:\n```\n{}\n```", truncate(ctx, 200))
                } else {
                    format!("```\n{}\n```", truncate(resolution, 200))
                };
                out.push_str(&format!("**Fix:**\n{fix}\n\n"));
            } else {
                out.push_str("**Fix:** Not yet resolved — investigate manually.\n\n");
            }
        }
    }

    let _ = fs::write(&path, out);
}

/// Generate the global cross-project troubleshooting protocol.
fn generate_global_protocol(analysis: &EcosystemAnalysis, projects_dir: &Path) {
    let path = projects_dir.join(".troubleshooting-global.md");
    let mut out = String::new();

    out.push_str("# Cross-Project Troubleshooting Protocol\n\n");
    out.push_str(&format!(
        "> Auto-generated by orrchestrator retrospect engine. {} projects scanned, {} total errors.\n\n",
        analysis.total_projects_scanned, analysis.total_errors_ecosystem,
    ));

    // Top error categories
    if !analysis.top_categories.is_empty() {
        out.push_str("## Error Category Distribution\n\n");
        out.push_str("| Category | Count |\n|----------|-------|\n");
        for (cat, count) in &analysis.top_categories {
            out.push_str(&format!("| {} | {} |\n", capitalize(cat.label()), count));
        }
        out.push_str("\n");
    }

    // Cross-project patterns
    if !analysis.cross_project_patterns.is_empty() {
        out.push_str("## Cross-Project Patterns\n\n");
        out.push_str("These error patterns appear in multiple projects — likely systemic issues.\n\n");

        for pattern in &analysis.cross_project_patterns {
            let projects_str = pattern.seen_in_projects.join(", ");
            let status = if pattern.resolved { "RESOLVED" } else { "OPEN" };
            out.push_str(&format!(
                "### [{status}] {} — `{}`\n\n",
                capitalize(pattern.category.label()),
                truncate(&pattern.fingerprint, 50),
            ));
            out.push_str(&format!("**Affected projects:** {projects_str}\n"));
            out.push_str(&format!("**Occurrences:** {}\n\n", pattern.occurrence_count));
            out.push_str(&format!("**Symptom:**\n```\n{}\n```\n\n", truncate(&pattern.sample_context, 150)));

            if let Some(ref resolution) = pattern.resolution {
                out.push_str(&format!("**Known fix:**\n{}\n\n", truncate(resolution, 200)));
            }
        }
    }

    // Per-project summary table
    if !analysis.per_project.is_empty() {
        out.push_str("## Project Health Summary\n\n");
        out.push_str("| Project | Errors | Unique | Resolved | Rate |\n");
        out.push_str("|---------|--------|--------|----------|------|\n");
        for proj in &analysis.per_project {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {:.0}% |\n",
                proj.project_name,
                proj.total_occurrences,
                proj.unique_errors,
                (proj.resolution_rate * proj.unique_errors as f64) as usize,
                proj.resolution_rate * 100.0,
            ));
        }
        out.push_str("\n");
    }

    let _ = fs::write(&path, out);
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max { s.to_string() }
    else { format!("{}...", &s[..max]) }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

fn format_duration(secs: f64) -> String {
    if secs < 60.0 { format!("{:.0}s", secs) }
    else if secs < 3600.0 { format!("{:.1}m", secs / 60.0) }
    else { format!("{:.1}h", secs / 3600.0) }
}
