pub mod agent;
pub mod audit;
pub mod backend;
pub mod config;
pub mod diff_log;
pub mod feedback;
pub mod git;
pub mod intake_review;
pub mod output_parser;
pub mod plan_parser;
pub mod process_manager;
pub mod project;
pub mod provider;
pub mod remote;
pub mod session;
pub mod session_log;
pub mod usage;
pub mod windows;
pub mod vault;
pub mod workflow_status;

pub use agent::{AgentProfile, load_agents, agents_dir};
pub use audit::{AuditEntry, ChunkCoordinate, compute_source_hash, write_audit_entry, load_audit_entries};
pub use backend::{BackendKind, BackendsConfig, is_provider_available};
pub use provider::{ProviderConfig, ProviderKind};
pub use config::Config;
pub use feedback::{save_and_route_feedback, CONTINUE_DEV_PROMPT, FeedbackItem, FeedbackStatus, FeedbackType, load_feedback_items, submit_feedback, delete_feedback, create_draft, create_append_draft, mark_as_processing, mark_as_processed, mark_as_routed, check_processing_complete, write_feedback_metadata, set_feedback_type, tmux_session_status, truncate_inbox_if_large, trim_completed_entries};
pub use output_parser::{analyze_output, infer_state, OutputSignal};
pub use process_manager::ProcessManager;
pub use plan_parser::{parse_plan, parse_status_marker, PlanPhase, PlanFeature, FeatureStatus, RemovalContext, MoveDirection, move_feature_in_plan, append_feature_to_plan, mark_verified_in_plan};
pub use diff_log::{DiffEntry, diff_log_path, append_diff, load_diffs, load_all_diffs};
pub use project::{list_directory, load_deprecated, load_projects, package_as_v1, update_feature_status_in_plan, ColorTag, DirEntry, Project, ProjectMeta, RoadmapItem, Scope, Temperature};
pub use session::{ExternalSession, Session, SessionState};
pub use usage::{RateLimitConfig, UsageTracker};
pub use intake_review::{IntakeReview, IntakeReviewFile, load_intake_review, load_review_at, write_intake_decision};
pub use workflow_status::{WorkflowStatus, WorkflowAgentStatus, load_workflow_status};
